### ISSUE TITLE
Things to optimize

### ISSUE THREAD

**Issue by elasticroentgen** [Ramshreyas/RadicleBackup#1]
Based on our TG convo, here things i would optimize:

1. `github_backup/Dockerfile` - add `apt-get clean` to line 8 to make sure the image size keeps small
2. Make the directory `/root/backup` in `radicle_push` configurable. 

Other than this i think it's ok.

**Comment by Ramshreyas** [comment]
`apt-get clean` added and radicle backup directory made configurable: https://github.com/Ramshreyas/RadicleBackup/commit/f52cacfb7f668d5de43defccebe0ca9b82019d77
